version: '3.8'

services:
  stkweight:
    build: .
    container_name: stkweight
    ports:
      - "8012:80" # 将主机8080端口映射到容器的80端口

    restart: always # 容器退出或Docker守护进程重启时，总是重新启动容器

networks:
  webnet:
    driver: bridge
